"""added source in user and source table

Revision ID: 15bc22287acc
Revises: 72d7fe0e5649
Create Date: 2026-01-10 12:37:07.509708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bc22287acc'
down_revision: Union[str, Sequence[str], None] = '72d7fe0e5649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('AUDIO', 'YOUTUBE', 'DOCUMENTS', name='source_type'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    # ### end Alembic commands ###
